<?php

namespace Hollo\CasimBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WheelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WheelRepository extends EntityRepository
{
}